name: Merge Conflict Checker

on:
  pull_request:
    branches:
      - main

jobs:
  merge-conflict-check:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        cd frontend
        npm install

    - name: Check for merge conflicts
      run: |
        cd frontend
        git fetch origin
        git checkout main
        git merge --no-commit --no-ff "origin/${{ github.event.pull_request.head.ref }}"
        if [ -n "$(git status --porcelain)" ]; then
          echo "ERROR: Merge conflicts detected. Please resolve conflicts before merging."
          exit 1
        fi
